org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.configuration-cache=false
org.gradle.caching=true
org.gradle.parallel=false
net.minecraftforge.gradle.merge-source-sets=false
minecraft_version=1.10.2
minecraft_version_range=[1.10.2]
forge_version=12.18.3.2511
mapping_channel=stable
mapping_version=29-1.10.2
loader_name=forge
loader_code=1
java_version=8
java_toolchain_version=8.0.502+7
gradle_java_version=17
mod_id=skysterrainsmootherbop
release_repository=MinecraftModDevelopmentMods/SkysTerrainSmoother-BiomesOPlenty-Addon
release_enabled=false
curseforge_project_id=
mod_name=Sky's Terrain Smoother - Biomes O Plenty
mod_license=LGPL-2.1-only
mod_version=0.1.0.110021
mod_group=zone.moddev.mc.skysterrainsmootherbop
mod_authors=SkyBlade1978
mod_description=Smooths new Biomes O Plenty surfaces with matching grass and soil slabs, steps and corners.
